name: getx_clean_boilerplate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  get_storage: ^2.0.2
  logger: ^1.0.0
  flutter: 
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies: 
  lints: 1.0.1
  flutter_test: 
    sdk: flutter
  build_runner: ^1.12.2
  json_serializable: ^4.0.3

flutter: 
  uses-material-design: true

